### ISSUE TITLE
Deployment Task never finishes

### ISSUE THREAD

**Issue by phidol** [vercel/vercel-azure-devops-extension#32]
Starting with version 1.4.0 the deployment task never finishes and the task will time out eventually.

For the moment this can be avoided by pinning the task to version 1.3.0 and everything should work as expected:
`task: vercel-deployment-task@1.3.0` instead of `task: vercel-deployment-task@1`

**Comment by Paulshaju** [comment]
Thanks for the solution! It worked after changing the version.

**Comment by akay0214** [comment]
I don't use yaml, so I cannot revert it. How can I fix that?
![image](https://github.com/user-attachments/assets/7e7fbb82-8124-44c9-bfa7-3918ad5a2d95)

**Comment by phidol** [comment]
Was fixed with latest version 1.6.0. No pinning of the version required anymore.
@akay0214 You're pipeline should work again as is just as of now!
